site_name: Moje projekty
site_author: Sebastian Strzelczyk
site_url: https://sebstr2358.github.io/ai_portfolio/
site_description: >-
  Portfolio moich wspaniałych projektów z Data Science i AI!

repo_name: sebstr2358/ai_portfolio
repo_url: https://github.com/sebstr2358/ai_portfolio

theme:
  name: material
  palette:
    primary: lime
    accent: light green
  features:
    - content.code.annotate # 
  

nav:
  - Strona Domowa: index.md
  - Bieżący projekt:
      - "Calculate_insurance_app": calculate_insurance_app/index.md
  - Poprzednie projekty:
      - "ChatGPT": chat_gpt/index.md
      - "JustJoinIt": just_join_it/index.md
      - "Filter_survey_app": filter_survey_app/index.md
      - "Titanic": titanic/index.md
      - "Iris": iris/index.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


  
