site_name: Moje projekty
site_author: Sebastian Strzelczyk
site_url: https://sebstr2358.github.io/ai_portfolio/
site_description: >-
    Portfolio moich wspaniałych projektów z Data Science i AI!

repo_name: sebstr2358/ai_portfolio
repo_url: https://github.com/sebstr2358/ai_portfolio

theme:
  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
- Strona Domowa: index.md
- Poprzednie projekty:
  - "Filter_survey_app": filter_survey_app/index.md
  - "Titanic": titanic/index.md
  - "Iris": iris/index.md

markdown_extensions:
- attr_list
- md_in_html
- pymdownx.blocks.caption

plugins:
   - glightbox

plugins:
   - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
       background: white
       shadow: true
       manual: false

  